name: "Combine Dependabot PRs"
on:
  workflow_dispatch:

jobs:
  combine-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: maadhattah/combine-dependabot-prs@aecc949b306f1ca346aa2e96729eb652f9797ca7 # main
        with:
          branchPrefix: "dependabot"
          mustBeGreen: true
          combineBranchName: "combined-prs"
          ignoreLabel: "nocombine"
          baseBranch: "master"
          openPR: true
          allowSkipped: false